name: Bike Point Ingestion

on:
  # every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  # button to trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Bike Point Environment DES4
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v2
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'
  
      - name: Install pacakages
        run: pip install -r requirements.txt
  
      - name: Run Python Script
        env: 
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          bucket: ${{secrets.bucket}}
        run: python main.py
        
